### ISSUE TITLE
Visibility bug with certain documents

### ISSUE THREAD

**Issue by AbanoubG** [dbishai/orthodox-presenter#14]
There appears to be a bug regarding the visibility of certain documents. 
For example, when opening the Liturgy of the Word, the Hymn of the Intercessions defaults as collapsed (visibility: "false") despite the [document](https://github.com/dbishai/orthodox-presenter/blob/dev/docs/hymns/hymn_intercessions_liturgy_of_the_word.json) not having the visible tag at all. 

Furthermore, the hymn of Hail to Mary the Queen to be chanted after the Hymn of Blessing has a visibility tag of false, indicating that it should be defaulted as collapsed and yet, in several instances, it appears uncollapsed. 

To replicate the issue, follow the steps below
Liturgies →St. Basil → Offering of the Lamb (Hail to Mary the Queen; Shere Maria) should appear collapsed. ✓

Then switch to Liturgy of the Word; the Hymn of the Intercessions appears collapsed. ✗

If the user then goes to the Liturgy of the Faithful, they will notice that the Orthodox Creed also appears collapsed. ✗

In addition to this, if the user switches to Matins or Vespers, the Lord's Prayer also appears collapsed. ✗

This was tested in Chrome as well as in Incognito mode.

[Reference commit](https://github.com/dbishai/orthodox-presenter/commit/55d724200615786b9de6c40b2c0ecead3a19604f)

**Comment by dbishai** [comment]
Nice catch! Found the bug. Thanks for the detailed report.

**Comment by dbishai** [comment]
this should be fixed now
