### ISSUE TITLE
Matins not showing appropriate litanies

### ISSUE THREAD

**Issue by AbanoubG** [dbishai/orthodox-presenter#16]
It seems as though there is a bug regarding the display of certain litanies regarding the Matins service. For example, when opening the Matins service on a Wednesday (weekday), the litany of the Sick and the Litany of the Travelers should be displayed however it displays the Litany of the Departed. Furthermore, on Saturday, when the Litany of the Departed should be prayed for Matins service, it displays the Litany of the Sick. 

In addition to this, on Sundays when the Litany of the Travelers should be omitted, it still displays it as well as not displaying the Litany of the Oblations.

These were the following dates used to test each of the scenarios above to ensure the error was consistent. 
1/24/18 (Wednesday) + 1/31/18 (Wednesday)
1/20/18 (Saturday) + 1/27/18 (Saturday)
1/21/18 (Sunday) + 1/28/18 (Sunday)

We might also have to take into consideration, feasts that are on a weekday.

**Comment by dbishai** [comment]
Good catch. Should be fixed now
