### ISSUE TITLE
Uncaught TypeError | Reference Commit #4d42d29

### ISSUE THREAD

**Issue by AbanoubG** [dbishai/orthodox-presenter#26]
[Commit #4d42d29](https://github.com/dbishai/orthodox-presenter/commit/4d42d298097e9734abed96ef92b5189a64bad144) seems to have caused an error resulting in an issue loading Orthodox Presenter. 

Prior to pulling aforementioned commit, no issues were apparent. Issue seems to be isolated to that specific commit. This can be confirmed by reverting back to the previous commit and testing it that way. 

**Chrome Verison 65.0.3325.181**
**Chrome Console Log**
```
Uncaught TypeError: Cannot read property 'slice' of undefined
    at downloadAsync (DocumentStore.js:48)
    at load (DocumentStore.js:34)
    at Object.getDocuments (DocumentStore.js:94)
    at Object.render (NavMenu.react.js:79)
    at ReactCompositeComponent.js:793
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
```
**DocumentStore** lines 27-51
```
function load(category, attributes) {
    if (category == null) {
        var docs = DocumentBuilder.autoLoad(attributes);
    } else {
        lastCategory = category;
        var docs = DocumentBuilder.build(category, attributes);
    }
    downloadAsync(docs);
}

function refresh(attributes) {
    load(lastCategory, attributes);
}

function downloadAsync(docs) {
    /*
    Using Deferred Objects, return when all downloads finish. Each resource is only requested once. On Success,
    notify components of change.
    */

    // use slice() to copy array by value
    var docsUnique = $.unique(docs.slice())
    var promises = [];
    var fileDir = "docs/";
    var fileType = ".json";
```

**Comment by dbishai** [comment]
Hmm, I just tested and was not able to replicate the issue. Does this happen on the initial page load? Can you give a list of steps to reproduce the issue?

**Comment by AbanoubG** [comment]
Yes.. It appears to occur on the initial page load. In term of reproducing it, all I did was pull the recent comment and from then on it hasn't been loading. I then went back to the previous version of the DocumentStore and it works just fine

**Comment by AbanoubG** [comment]
Nope.. You are correct. For whatever reason I was getting that issue but a rebuild seems to have resolved it. Should have done that before. My apologies.
